# Spam Ham Detection Using BERT and Tensorflow

### <u>Project Summary</u>

### <u>GitHub Link</u>
[Click Here](https://github.com/ajitmane36/spam-ham-detection-bert-tensorflow.git)

### <u>Problem Statement</u>

- The data is related to the classification of emails into spam or ham (non-spam). The goal of this project is to develop a model using BERT and TensorFlow to predict whether an email is spam or not based on its content. By fine-tuning a pre-trained BERT model, the objective is to enhance the accuracy and efficiency of email classification, ensuring that legitimate emails are delivered to the inbox while spam is effectively filtered out.

### <u>Data Description</u>

- **text**: Description of the email content (text).
- **label**: Indicates whether the email is spam (1) or not (0).

In [88]:
# Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

# filter warnings
import warnings
warnings.filterwarnings('ignore')

In [89]:
# Dataset Loading
df=pd.read_csv(r"C:\Users\ajitm\Downloads\DS Projects\Deep Larning Projects\1. Text Classification Using BERT & Tensorflow\spam_emails_data.csv")
df.set_index('Category')

Message
Category                                                   
ham       Go until jurong point, crazy.. Available only ...
ham                           Ok lar... Joking wif u oni...
spam      Free entry in 2 a wkly comp to win FA Cup fina...
ham       U dun say so early hor... U c already then say...
ham       Nah I don't think he goes to usf, he lives aro...
...                                                     ...
spam      This is the 2nd time we have tried 2 contact u...
ham                    Will ü b going to esplanade fr home?
ham       Pity, * was in mood for that. So...any other s...
ham       The guy did some bitching but I acted like i'd...
ham                              Rofl. Its true to its name

[5572 rows x 1 columns]

In [90]:
# Fist five observations
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [91]:
# Last five observations
df.tail()

Category                                            Message
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

#### <u>Data Inispection</u>

In [93]:
# Shape of dataset
df.shape
print(f'Dataset has {df.shape[0]} observations and {df.shape[1]} columns.')

Dataset has 5572 observations and 2 columns.


In [94]:
# Dataset columns
print(df.columns.tolist())

['Category', 'Message']


In [95]:
# Basic information of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [96]:
# Basic description of dataset
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

- Dataset having 4825 Ham observations and 747 spam observations.

In [98]:
# Cehcking  duplicates value in each feature
duplicates_df=pd.DataFrame({'columns':df.columns, 'number_of_duplicates': df.duplicated().sum()}).sort_values(by='number_of_duplicates', ascending=False)
print(duplicates_df)
print(f'Dataset having {df.duplicated().sum()} duplicates values.')

    columns  number_of_duplicates
0  Category                   415
1   Message                   415
Dataset having 415 duplicates values.


In [99]:
# Checking missing values
null_df=pd.DataFrame({'columns': df.columns, 'num_of_nulls': df.isna().sum()})
print(null_df )
print(f'Dataset have {df.isna().sum()} null values.')

           columns  num_of_nulls
Category  Category             0
Message    Message             0
Dataset have Category    0
Message     0
dtype: int64 null values.
